<?php

declare (strict_types=1);
namespace Php_Office\Php_Spreadsheet\Calculation\Engine;

class Logger
{
    /**
     * Flag to determine whether a debug log should be generated by the calculation engine
     *        If true, then a debug log will be generated
     *        If false, then a debug log will not be generated.
     */
    private bool $write_debug_log = false;
    /**
     * Flag to determine whether a debug log should be echoed by the calculation engine
     *        If true, then a debug log will be echoed
     *        If false, then a debug log will not be echoed
     * A debug log can only be echoed if it is generated.
     */
    private bool $echo_debug_log = false;
    /**
     * The debug log generated by the calculation engine.
     *
     * @var string[]
     */
    private array $debug_log = [];
    /**
     * Instantiate a Calculation engine logger.
     */
    public function __construct(
        /**
         * The calculation engine cell reference stack.
         */
        private readonly Cyclic_Reference_Stack $cell_stack
    )
    {
    }
    /**
     * Enable/Disable Calculation engine logging.
     */
    public function set_write_debug_log(bool $write_debug_log): void
    {
        $this->write_debug_log = $write_debug_log;
    }
    /**
     * Return whether calculation engine logging is enabled or disabled.
     */
    public function get_write_debug_log(): bool
    {
        return $this->write_debug_log;
    }
    /**
     * Enable/Disable echoing of debug log information.
     */
    public function set_echo_debug_log(bool $echo_debug_log): void
    {
        $this->echo_debug_log = $echo_debug_log;
    }
    /**
     * Return whether echoing of debug log information is enabled or disabled.
     */
    public function get_echo_debug_log(): bool
    {
        return $this->echo_debug_log;
    }
    /**
     * Write an entry to the calculation engine debug log.
     */
    public function write_debug_log(string $message, mixed ...$args): void
    {
        //    Only write the debug log if logging is enabled
        if ($this->write_debug_log) {
            $message = sprintf($message, ...$args);
            //* @phpstan-ignore-line
            $cell_reference = implode(' -> ', $this->cell_stack->show_stack());
            if ($this->echo_debug_log) {
                echo $cell_reference, $this->cell_stack->count() > 0 ? ' => ' : '', $message, PHP_EOL;
            }
            $this->debug_log[] = $cell_reference . ($this->cell_stack->count() > 0 ? ' => ' : '') . $message;
        }
    }
    /**
     * Write a series of entries to the calculation engine debug log.
     *
     * @param string[] $args
     */
    public function merge_debug_log(array $args): void
    {
        if ($this->write_debug_log) {
            foreach ($args as $entry) {
                $this->write_debug_log($entry);
            }
        }
    }
    /**
     * Clear the calculation engine debug log.
     */
    public function clear_log(): void
    {
        $this->debug_log = [];
    }
    /**
     * Return the calculation engine debug log.
     *
     * @return string[]
     */
    public function get_log(): array
    {
        return $this->debug_log;
    }
}